name = "Light Overlay (Rift/Forge/Fabric)"
filename = "light-overlay-5.6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3155/937/light-overlay-5.6.1.jar"
hash-format = "murmur2"
hash = "1173197376"

[update]
[update.curseforge]
file-id = 3155937
project-id = 325492
release-channel = "beta"
